apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-nn-pv
  namespace: hadoop
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/hadoop-nn"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-dn-pv
  namespace: hadoop
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/hadoop-dn"