apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode
  namespace: hadoop
spec:
  selector:
    matchLabels:
      app: hadoop
      component: datanode
  template:
    metadata:
      labels:
        app: hadoop
        component: datanode
    spec:
      initContainers:
      - name: init-datanode-dir
        image: busybox
        command: ['sh', '-c', 'mkdir -p /hadoop/dfs/data && chmod -R 777 /hadoop/dfs']
        volumeMounts:
        - name: datanode-storage
          mountPath: /hadoop/dfs/data
      containers:
      - name: datanode
        image: apache/hadoop:3.4.1
        command: ["hdfs", "datanode"]
        env:
        - name: HADOOP_CONF_DIR
          value: /opt/hadoop/etc/hadoop
        ports:
        - containerPort: 9864
        volumeMounts:
        - name: hadoop-config
          mountPath: /opt/hadoop/etc/hadoop
        - name: datanode-storage
          mountPath: /hadoop/dfs/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "6Gi"
            cpu: "1500m"
      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-config
      - name: datanode-storage
        persistentVolumeClaim:
          claimName: datanode-pvc