apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  POSTGRES_USER: lab_user
  POSTGRES_PASSWORD: lab_pass
  POSTGRES_DB: lab_db
  POSTGRES_HOSTNAME: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_TABLE_SOURCE: source_data

  JAR_PATH: datamart-csv-fat.jar
  SPARK_MASTER: local[*]
  SPARK_DRIVER_MEMORY: 1g
  SPARK_EXECUTOR_MEMORY: 1g
  SPARK_DRIVER_CORES: "1"
  SPARK_EXECUTOR_CORES: "1"
  SPARK_NUM_EXECUTORS: "1"

  MODEL_PATH: src/models/kmeans_model
  SPARK_APP_NAME: Lab7App
  PROCESSED_CSV_PATH: processed_data.csv