apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs
      component: namenode
  template:
    metadata:
      labels:
        app: hdfs
        component: namenode
    spec:
      hostname: namenode
      containers:
      - name: namenode
        image: apache/hadoop:3.4.1
        imagePullPolicy: IfNotPresent
        env:
        - name: HADOOP_HOME
          value: "/opt/hadoop"
        - name: HADOOP_CONF_DIR
          value: "/opt/hadoop/etc/hadoop"
        volumeMounts:
        - name: hdfs-config-volume
          mountPath: /opt/hadoop/etc/hadoop
        - name: namenode-data
          mountPath: /opt/hadoop/data/nameNode
        - name: start-script
          mountPath: /start-hdfs.sh
          subPath: start-hdfs.sh
        command: ["/bin/bash", "/start-hdfs.sh"]
        ports:
        - containerPort: 9870
        - containerPort: 9000
      volumes:
      - name: hdfs-config-volume
        configMap:
          name: hdfs-config
      - name: namenode-data
        emptyDir: {}
      - name: start-script
        configMap:
          name: hdfs-scripts
