apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs
      component: datanode
  template:
    metadata:
      labels:
        app: hdfs
        component: datanode
    spec:
      containers:
      - name: datanode
        image: apache/hadoop:3.4.1
        imagePullPolicy: IfNotPresent
        env:
        - name: HADOOP_HOME
          value: "/opt/hadoop"
        - name: HADOOP_CONF_DIR
          value: "/opt/hadoop/etc/hadoop"
        volumeMounts:
        - name: hdfs-config-volume
          mountPath: /opt/hadoop/etc/hadoop
        - name: datanode-data
          mountPath: /opt/hadoop/data/dataNode
        - name: init-script
          mountPath: /init-datanode.sh
          subPath: init-datanode.sh
        command: ["/bin/bash", "/init-datanode.sh"]
        ports:
        - containerPort: 9864
      volumes:
      - name: hdfs-config-volume
        configMap:
          name: hdfs-config
      - name: datanode-data
        emptyDir: {}
      - name: init-script
        configMap:
          name: hdfs-scripts
