apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    app: hdfs
    component: namenode
spec:
  selector:
    app: hdfs
    component: namenode
  ports:
    - name: rpc
      port: 9000
      targetPort: 9000
    - name: web
      port: 9870
      targetPort: 9870