apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
data:
  SPARK_MASTER: "local[*]"
  SPARK_DRIVER_MEMORY: "1g"
  SPARK_EXECUTOR_MEMORY: "1g"
  SPARK_DRIVER_CORES: "1"
  SPARK_EXECUTOR_CORES: "1"
  SPARK_NUM_EXECUTORS: "1"
  SPARK_JAVA_OPTS: "-Dfile.encoding=UTF-8"

  MODEL_PATH: "src/models/kmeans_model"
  HDFS_RAW_PATH: "hdfs://namenode:9000/app/sql/source_data.csv"
  HDFS_RAW_PATH_SCALA: "hdfs://namenode:9000/app/sql/source_data.csv"
  HDFS_PROCESSED_PATH: "/app/processed"
  JAR_PATH: "datamart-csv-fat.jar"
